[package]
name = "rstats"
version = "0.2.2"
authors = ["Libor Spacek"]
edition = "2018"
description = "Simple Statistics: Means, Median, Correlations"
homepage = "https://github.com/liborty/rustats"
repository = "https://github.com/liborty/rustats"
license = "Apache-2.0"
keywords = ["statistics","means","median","correlation","time-dependent"]
categories = ["science","mathematics"]
include = [
    "src/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE"
]
[badges]
maintenance = { status = "actively-developed" }
[lib]
[dependencies]
anyhow = "^1"
