[package]
name = "rstats"
version = "1.2.42"
authors = ["Libor Spacek"]
edition = "2021"
description = "Statistics, Linear Algebra, Cholesky Matrix Decomposition, Mahalanobis Distance, Householder Decomposition, Hulls, Information Measures, Multidimensional Data Analysis, Machine Learning, Multithreading and more"
readme = "README.md"
homepage = "https://github.com/liborty/rstats"
repository = "https://github.com/liborty/rstats"
license = "Apache-2.0"
keywords = ["machine-learning","statistics","linear-algebra","geometric-median","data-analysis"]
categories = ["science","mathematics","algorithms","visualization","rust-patterns"]
include = [
    "src/*.rs", 
    "Cargo.toml",
    "README.md",
    "LICENSE"
]
[badges]
maintenance = { status = "actively-developed" }
[lib]
[dependencies]
rayon = "1.7"
indxvec = "1.5"
medians = "2.2"   
ran = "1.1" # {path = "../random"}
[dev-dependencies]
times = "1.0"
