[package]
name = "rstats"
version = "0.1.1"
authors = ["Libor Spacek"]
edition = "2018"
description = "Simple Statistics"
homepage = "https://github.com/liborty/rustats"
repository = "https://github.com/liborty/rustats"
license-file = "LICENSE"
keywords = ["statistics","means","median","correlation","time-dependent"]
categories = ["science","mathematics"]

[profile.test]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
incremental = true
rpath = false

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = true
rpath = false

[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
incremental = true
rpath = false

[lib]
[dependencies]
anyhow = "^1"
