[package]
name = "rstats"
version = "0.8.0"
authors = ["Libor Spacek"]
edition = "2018"
description = "Statistical Measures, Vector Algebra, Geometric Median, Data Analysis and Machine Learning"
readme = "README.md"
homepage = "https://github.com/liborty/rstats"
repository = "https://github.com/liborty/rstats"
license = "Apache-2.0"
keywords = ["statistics","vector-algebra","geometric-median","machine-learning","multidimensional"]
categories = ["science","mathematics","algorithms","visualization","concurrency"]
include = [
    "src/*.rs",
    "tests/*.rs",
    "benches/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE"
]
[badges]
maintenance = { status = "actively-developed" }
[lib]
[dependencies]
indxvec = "^0.2"
anyhow = "^1"

[dev-dependencies]
devtimer = "4"

[[bench]]
name = "mybenchmark"
harness = false
