[package]
name = "rstats"
version = "0.4.0"
authors = ["Libor Spacek"]
edition = "2018"
description = "Simple Statistics: Means, Median, Correlations"
homepage = "https://github.com/liborty/rustats"
repository = "https://github.com/liborty/rustats"
license = "Apache-2.0"
keywords = ["statistics","vectors","geometric-median","n-dimensional","time-dependent"]
categories = ["science","mathematics","algorithms"]
include = [
    "src/*.rs",
    "tests/*.rs",
    "benches/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE"
]
[badges]
maintenance = { status = "actively-developed" }
[lib]
[dependencies]
anyhow = "^1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "mybenchmark"
harness = false
