[package]
name = "rstats"
version = "1.0.10"
authors = ["Libor Spacek"]
edition = "2021"
description = "Statistical Measures, Vector Algebra, Geometric Median, Data Analysis and Machine Learning"
readme = "README.md"
homepage = "https://github.com/liborty/rstats"
repository = "https://github.com/liborty/rstats"
license = "Apache-2.0"
keywords = ["machine-learning","statistics","vector-algebra","geometric-median","multidimensional"]
categories = ["science","mathematics","algorithms","visualization","rust-patterns"]
include = [
    "src/*.rs",
    "tests/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE"
]
[badges]
maintenance = { status = "actively-developed" }
[lib]
[dependencies]
indxvec = "^1"
anyhow = "^1"

[dev-dependencies]
devtimer = "4"
