name: compilation

on: push

jobs:
  build:  
    name: Rstats 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1    
      with:
        toolchain: stable 
    - run: cargo check -r    
