name: tests

on: push

jobs:
  build:  
    name: Rstats 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable    
    - run: cargo test --release -- --nocapture --color always --test-threads=1  
    - run: cargo test -r timing_gm -- --nocapture
